# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.obed.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0012_auto_20190603_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=b'img/site/obed/award', verbose_name='\u0438\u043a\u043e\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='card_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 298\xd7140 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', null=True, upload_to=b'img/site/obed/establishment/', verbose_name='\u0424\u043e\u0442\u043e \u0434\u043b\u044f \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='corporative_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/obed/corporative', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, upload_to=irk.obed.models.type_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
