# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0014_auto_20200331_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043e\u043a\u0440\u0443\u0433',
                'verbose_name_plural': '\u043e\u043a\u0440\u0443\u0433\u0430',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='delivery_price_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0411\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u0430\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 \u043e\u0442'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='delivery_districts',
            field=models.ManyToManyField(to='obed.Okrug', verbose_name='\u041e\u043a\u0440\u0443\u0433'),
        ),
    ]
