# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 08:10
from __future__ import unicode_literals

from django.db import migrations


okrug_names = [
    #u'Ленинский', u'Свердловский', u'Октябрьский', u'Правобережный'
]

def create_okrugs(apps, schema_editor):
    Okrug = apps.get_model('obed', 'Okrug')

    for name in okrug_names:
        okrug = Okrug()
        okrug.name = name
        okrug.save()

class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0015_auto_20200408_0805'),
    ]

    operations = [
        migrations.RunPython(create_okrugs),
    ]
