# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_auto_20200713_1654'),
        ('obed', '0017_auto_20200424_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TildaArticle',
            fields=[
                ('basematerial_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='obed_tildaarticle_related', serialize=False, to='news.BaseMaterial')),
                ('tilda_content', models.TextField(blank=True, verbose_name='HTML-\u043a\u043e\u0434 \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('styles', models.TextField(blank=True, verbose_name='\u0421\u0442\u0438\u043b\u0438')),
                ('scripts', models.TextField(blank=True, verbose_name='\u0421\u043a\u0440\u0438\u043f\u0442\u044b')),
                ('archive', irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.news.models.tilda_upload_to, verbose_name='\u0418\u043c\u043f\u043e\u0440\u0442 \u0438\u0437 \u0444\u0430\u0439\u043b\u0430')),
                ('image', models.ImageField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 1180\u0445560 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0428\u0438\u0440\u043e\u043a\u043e\u0444\u043e\u0440\u043c\u0430\u0442\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('image_label', models.CharField(blank=True, max_length=255, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u044c \u0434\u043b\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u0441\u0442\u0430\u0442\u044c\u044f \u043e\u0431\u0435\u0434\u0430 (\u0422\u0438\u043b\u044c\u0434\u0430)',
                'verbose_name_plural': '\u0441\u0442\u0430\u0442\u044c\u0438 \u043e\u0431\u0435\u0434\u0430 (\u0422\u0438\u043b\u044c\u0434\u0430)',
            },
            bases=('news.basematerial',),
        ),
    ]
