# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0011_auto_20181211_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerTerrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u043b\u0435\u0442\u043d\u044f\u044f \u0432\u0435\u0440\u0430\u043d\u0434\u0430',
                'verbose_name_plural': '\u043b\u0435\u0442\u043d\u0438\u0435 \u0432\u0435\u0440\u0430\u043d\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='summer_terrace',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u0412\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u0441\u043f\u0438\u0441\u043a\u0435 \u043b\u0435\u0442\u043d\u0438\u0445 \u0432\u0435\u0440\u0430\u043d\u0434'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='summer_terrace_description',
            field=models.TextField(blank=True, default=b'', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u043b\u0435\u0442\u043d\u0435\u0439 \u0432\u0435\u0440\u0430\u043d\u0434\u044b'),
        ),
        migrations.AddField(
            model_name='summerterrace',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_summer_terrace', to='obed.Establishment', verbose_name='\u0417\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u0435'),
        ),
    ]
