# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0013_auto_20200210_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430',
                'verbose_name_plural': '\u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='delivery',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u0412\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u0441\u043f\u0438\u0441\u043a\u0435 \u0434\u043e\u0441\u0442\u0430\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='delivery_description',
            field=models.TextField(blank=True, default=b'', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='establishment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_delivery', to='obed.Establishment', verbose_name='\u0417\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u0435'),
        ),
    ]
