# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obed', '0016_auto_20200408_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='delivery_districts',
            field=models.ManyToManyField(blank=True, to='obed.Okrug', verbose_name='\u041e\u043a\u0440\u0443\u0433'),
        ),
    ]
