# Generated by Django 3.2.5 on 2021-07-05 09:33

from django.db import migrations, models
import utils.db.models.fields.color
import utils.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('slugs', models.CharField(help_text='Должен быть уникальным и не содержать в себе другие алиасы. Например news-some не подойдет', max_length=50, unique=True, verbose_name='Алиасы')),
                ('position', models.IntegerField(db_index=True, verbose_name='Позиция')),
                ('menu_class', models.CharField(blank=True, max_length=15, verbose_name='Класс')),
                ('in_menu', models.BooleanField(default=False, help_text='Если галочка стоит, то будет отображаться в основном меню, если нет то в списке "ещё"', verbose_name='В меню')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='Не отображается в меню вообще', verbose_name='Спрятан')),
                ('booking_visible', models.BooleanField(default=False, verbose_name='Выводить в бронировании')),
                ('mark_in_menu', models.BooleanField(default=False, verbose_name='В верхней строке')),
                ('highlight', models.BooleanField(default=False, verbose_name='Подсвечивать')),
                ('small', models.BooleanField(default=False, verbose_name='Уменьшенная шапка')),
                ('blogs_through_perms', models.BooleanField(default=False, verbose_name='Добавление/ред. блогов только через права.')),
                ('show_in_bar', models.BooleanField(default=False, help_text='Для внешних сайтов', verbose_name='Показывать в полосе навигации')),
                ('track_transition', models.BooleanField(default=False, help_text='Статистика хранится в Google.Analytics', verbose_name='Подсчитывать переходы')),
                ('icon', utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to='img/site/option/icon/', verbose_name='Иконка')),
                ('show_icon', models.BooleanField(default=False, verbose_name='Показывать иконку')),
                ('branding_image', utils.fields.file.ImageRemovableField(blank=True, help_text='Размеры изображения: 1920×250 пикселей', null=True, upload_to='img/site/adv/branding', verbose_name='Брендирование')),
                ('branding_color', utils.db.models.fields.color.ColorField(blank=True, help_text='В формате #13bf99', max_length=6, null=True, verbose_name='Цвет фона брендирования')),
                ('widget_image', utils.fields.file.ImageRemovableField(blank=True, help_text='Выводится справа от меню', null=True, upload_to='img/site/adv/widgets', verbose_name='Изображение виджета')),
                ('widget_link', models.URLField(blank=True, null=True, verbose_name='Ссылка виджета')),
                ('widget_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст виджета')),
                ('image', utils.fields.file.FileRemovableField(blank=True, help_text='Размер по высоте 20px. Можно SVG. Заменяет текст в меню картинкой', null=True, upload_to='img/site/option/image/', verbose_name='Картинка вместо текста')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'db_table': 'options_site',
                'ordering': ['position'],
            },
        ),
    ]
