# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.profiles.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, upload_to=irk.profiles.models.get_user_image_path, verbose_name='\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
