# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.afisha.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0024_auto_20200122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, upload_to=irk.afisha.models.upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='map',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/afisha/maps', verbose_name='\u0421\u0445\u0435\u043c\u0430 \u0437\u0430\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='map',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/afisha/maps', verbose_name='\u0421\u0445\u0435\u043c\u0430 \u0437\u0430\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='prism',
            name='icon',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=b'img/site/afisha/prism', verbose_name='\u0438\u043a\u043e\u043d\u043a\u0430'),
        ),
    ]
