# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0025_auto_20200210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramblerevent',
            name='cast',
            field=models.CharField(max_length=1000),
        ),
    ]
