# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0026_auto_20201204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramblerevent',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
