# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 16:38
from __future__ import unicode_literals

from django.db import migrations

sql = """
INSERT INTO invoice_baseorder (id, price, created, updated, invoice_id, user_id ) SELECT id, price, created, updated, invoice_id, user_id FROM afisha_order;
INSERT INTO afisha_eventorder (baseorder_ptr_id, event_id) SELECT id, event_id FROM afisha_order;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0029_auto_20210311_1615'),
    ]

    operations = [
        migrations.RunSQL(sql)
    ]
