# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0030_auto_20210311_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
