# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irkutsk360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congratulation',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/site/irkutsk360/congratulation', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
