# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.news.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20170726_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='social_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 940x445', null=True, upload_to=irk.news.models.social_card_upload_to, verbose_name='\u0424\u043e\u043d \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='magazineauthor',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/magazine/author', verbose_name='\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
