# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181211_1133'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wishforconditions',
            managers=[
                ('conditions', django.db.models.manager.Manager()),
            ],
        ),
    ]
