# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_treasure_svg_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='treasure',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430'),
        ),
    ]
