# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201224_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
