# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_treasure_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u041a\u043e\u0434 \u0434\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043f\u0440\u0438\u0437\u0430'),
        ),
    ]
