# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_auto_20181127_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureDishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='\u0410\u043b\u0438\u0430\u0441')),
            ],
            options={
                'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0433\u0438\u0434\u0430',
                'verbose_name_plural': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0433\u0438\u0434\u0430',
            },
        ),
        migrations.AlterField(
            model_name='treasuredish',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='\u043e\u0442 1 \u0434\u043e 3'),
        ),
        migrations.AddField(
            model_name='treasuredish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landings.TreasureDishCategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
