# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0007_auto_20200210_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='main', max_length=100, unique=True, verbose_name='\u0410\u043b\u0438\u0430\u0441')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u0435',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043e \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u0435',
            },
        ),
    ]
