# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0009_article9may'),
    ]

    operations = [
        migrations.AddField(
            model_name='article9may',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
    ]
