# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.landings.models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0011_auto_20200515_0456'),
    ]

    operations = [
        #migrations.AlterField(
            #model_name='covidcard',
            #name='page',
            #field=models.ForeignKey(default=irk.landings.models.get_default_covid_page_id, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='landings.CovidPage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u0435'),
        #),
    ]
