# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.landings.models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0015_questionsgovernor'),
    ]

