# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishforconditions',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField( upload_to=b'img/site/weather/wishes/',),
        ),
        migrations.AlterField(
            model_name='wishforday',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField( upload_to=b'img/site/weather/wishes/',),
        ),
    ]
