# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 13:57
from __future__ import unicode_literals

from django.db import migrations
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishforconditions',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440 1920x440', upload_to=b'img/site/weather/wishes/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='wishforday',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440 1920x440', upload_to=b'img/site/weather/wishes/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
