# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_site_image'),
        ('adwords', '0004_auto_20190401_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='adword',
            name='sites',
            field=models.ManyToManyField(to='options.Site', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b\u044b'),
        ),
        migrations.AddField(
            model_name='adwordperiod',
            name='adword',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='adwords.AdWord'),
            preserve_default=False,
        ),
    ]
