# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_spamip_spamlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u043e\u0442\u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d'),
        ),
    ]
