# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irkutsk360', '0002_congratulation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='photo',
            field=models.ImageField(blank=True, help_text='60x60', upload_to='img/site/irkutsk360/congratulation', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
