# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adv', '0008_auto_20190212_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('clients', models.ManyToManyField(related_name='clients', to='adv.Client', verbose_name='\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0411\u0438\u0437\u043d\u0435\u0441 \u0430\u043a\u043a\u0430\u0443\u043d\u0442',
                'verbose_name_plural': '\u0411\u0438\u0437\u043d\u0435\u0441 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u044b',
            },
        ),
    ]
