# Generated by Django 2.2.16 on 2020-10-02 13:15

from django.db import migrations, models

from base.models_i.tasks import set_time_default


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200929_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_due',
            field=models.DateTimeField(default=set_time_default),
        ),
    ]
