# Generated by Django 3.1.2 on 2020-12-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201210_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-order'], 'verbose_name': 'Очередь', 'verbose_name_plural': 'Очереди'},
        ),
        migrations.AddField(
            model_name='queue',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отоброжения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидает'), ('O', 'Открыта'), ('H', 'Замороженно'), ('S', 'Решено'), ('C', 'Закрыто')], max_length=1, verbose_name='Статус'),
        ),
    ]
