# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0005_auto_20190611_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuredish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landings.TreasureDishCategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='treasuredish',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='obed.Establishment', verbose_name='\u0417\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u0435'),
        ),
    ]
