# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-10 10:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0008_covidpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article9May',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(db_index=True, default=True, verbose_name='\u0421\u043a\u0440\u044b\u0442\u0430\u044f')),
                ('title', models.CharField(max_length=300, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(blank=True, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('point', django.contrib.gis.db.models.fields.PointField(default='', null=True, spatial_index=False, srid=4326, verbose_name='\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u0430')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f 9 \u043c\u0430\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438 9 \u043c\u0430\u044f',
            },
        ),
    ]
