# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0010_article9may_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430')),
                ('visible', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c')),
            ],
            options={
                'verbose_name': 'COVID-19: \u041a\u0430\u0440\u0442\u043e\u0447\u043a\u0430',
                'verbose_name_plural': 'COVID-19: \u041a\u0430\u0440\u0442\u043e\u0447\u043a\u0438',
            },
        ),
        migrations.AlterModelOptions(
            name='covidpage',
            options={'verbose_name': 'COVID-19: \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': 'COVID-19: \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AddField(
            model_name='covidcard',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='landings.CovidPage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u0435'),
        ),
    ]
