# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0012_auto_20200713_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u0418\u043c\u044f')),
                ('text', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('is_visible', models.BooleanField(db_index=True, default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0411\u043b\u0430\u0433\u043e\u0434\u0430\u0440\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0411\u043b\u0430\u0433\u043e\u0434\u0430\u0440\u043d\u043e\u0441\u0442\u0438',
            },
        ),
    ]
