# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20200210_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=b'', max_length=190, verbose_name=b'\xd0\xad\xd0\xbb\xd0\xb5\xd0\xba\xd1\x82\xd1\x80\xd0\xbe\xd0\xbd\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xb0')),
                ('message_date', models.DateTimeField(null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb8 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xbf\xd0\xb8\xd1\x81\xd1\x8c\xd0\xbc\xd0\xb0')),
                ('date', models.DateField(null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd0\xb8\xd1\x81\xd1\x8c\xd0\xbc\xd0\xb0')),
                ('message_id', models.CharField(blank=True, default=b'', max_length=150)),
                ('hash', models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'\xd0\xa5\xd0\xb5\xd1\x88 \xd0\xbf\xd0\xb8\xd1\x81\xd1\x8c\xd0\xbc\xd0\xb0')),
                ('details', models.TextField(blank=True, default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0411\u0430\u0443\u043d\u0441-\u043f\u0438\u0441\u044c\u043c\u043e',
                'verbose_name_plural': '\u0411\u0430\u0443\u043d\u0441-\u043f\u0438\u0441\u044c\u043c\u0430',
            },
        ),
    ]
