# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_cabinet', '0001_initial'),
        ('profiles', '0005_bounceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adv_cabinet.BusinessAccount', verbose_name='\u0411\u0438\u0437\u043d\u0435\u0441 \u0430\u043a\u043a\u0430\u0443\u043d\u0442'),
        ),
    ]
