# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 07:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u043e\u043a',
                'verbose_name_plural': '\u0418\u0433\u0440\u043e\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('visible', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c')),
                ('price', models.PositiveSmallIntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('image', models.ImageField(upload_to='img/site/game/prize', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u0437',
                'verbose_name_plural': '\u041f\u0440\u0438\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='\u041d\u0430\u0448\u0435\u043b \u043a\u043b\u0430\u0434')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Gamer', verbose_name='\u0418\u0433\u0440\u043e\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441',
                'verbose_name_plural': '\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u043a\u0443\u043f\u043a\u0438')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Gamer', verbose_name='\u0418\u0433\u0440\u043e\u043a')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Prize', verbose_name='\u041f\u0440\u0438\u0437')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043a\u0443\u043f\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u043a\u0443\u043f\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('secret', models.CharField(max_length=100, verbose_name='\u041a\u043e\u0434')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('hint', models.CharField(default='', max_length=1000, verbose_name='\u041f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0430\u0434',
                'verbose_name_plural': '\u041a\u043b\u0430\u0434\u044b',
            },
        ),
        migrations.AddField(
            model_name='progress',
            name='treasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Treasure', verbose_name='\u041a\u043b\u0430\u0434'),
        ),
        migrations.CreateModel(
            name='ExpandGamer',
            fields=[
            ],
            options={
                'verbose_name': '\u0418\u0433\u0440\u043e\u043a',
                'proxy': True,
                'verbose_name_plural': '\u0418\u0433\u0440\u043e\u043a\u0438',
                'indexes': [],
            },
            bases=('game.gamer',),
        ),
        migrations.CreateModel(
            name='ExpandPrize',
            fields=[
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u0437',
                'proxy': True,
                'verbose_name_plural': '\u041f\u0440\u0438\u0437\u044b',
                'indexes': [],
            },
            bases=('game.prize',),
        ),
    ]
