# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200911_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='svg_emoji',
            field=models.CharField(default='', max_length=255, verbose_name='SVG emoji'),
        ),
    ]
