# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_instagramembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramembed',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False, verbose_name='Slug'),
        ),
    ]
