# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-18 11:53
from __future__ import unicode_literals

from django.db import migrations


# Этот запрос заполняет таблицу news_articleindex - создает
# ссылку для каждого материала из BaseMaterial
# Это нужно, чтобы в ленте материалов на индексе статей сразу появились
# все старые материалы, отсортированные по дате публикации

sql = """
INSERT IGNORE INTO news_articleindex(material_id, position)
SELECT id, unix_timestamp(timestamp(stamp, published_time))*1000000
FROM news_basematerial
WHERE stamp IS NOT NULL AND published_time IS NOT NULL;
"""

reverse_sql = 'DELETE FROM news_articleindex'

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_articleindex'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
