# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-16 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_fill_articleindex_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveentry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
