# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20190930_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basematerial',
            name='is_unkind',
        ),
    ]
