# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-27 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20191216_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hide_main_image',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u041e\u0442\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0433\u043b\u0430\u0432\u043d\u0443\u044e \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0443'),
        ),
    ]
