# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_auto_20200225_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special',
        ),
    ]
