# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_delete_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmeta',
            name='key',
            field=models.CharField(db_index=True, max_length=191, verbose_name='\u041f\u043e\u043b\u0435'),
        ),
    ]
