# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-30 12:01
from __future__ import unicode_literals

from django.db import migrations


sql = """
INSERT INTO news_block SET name = 'Закрепленные материалы раздела COVID-19',
slug = 'landings_covid_fixed_cards', position_count = '6'
"""

reverse_sql = "DELETE FROM news_block WHERE slug = 'landings_covid_fixed_cards'"

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_auto_20200713_1654'),
    ]

    operations = [
        #migrations.RunSQL(sql, reverse_sql)
    ]

