# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_auto_20210119_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rss_video_link',
            field=models.URLField(blank=True, default=b'', max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AddField(
            model_name='news',
            name='rss_video_preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'img/site/news/video_preview/', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e \u0434\u043b\u044f \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
