# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_auto_20170322_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branding',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440\u044b \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f: 1920\xd7600 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', null=True, upload_to=b'img/site/special/branding', verbose_name='\u0411\u0440\u0435\u043d\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=irk.utils.fields.file.FileRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f: 31x31', null=True, upload_to=b'img/site/news/subject/icon', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'svg'])], verbose_name='\u0438\u043a\u043e\u043d\u043a\u0430 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435 SVG'),
        ),
    ]
