# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_auto_20200210_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='person',
        ),
    ]
