# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_auto_20200210_1515'),
        ('tourism', '0007_utf8mb4_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourfirm',
            name='tour_order',
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.Place', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043e\u0442\u0434\u044b\u0445\u0430'),
        ),
        migrations.AddField(
            model_name='place',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_place', to='phones.Firms'),
        ),
    ]
