# Generated by Django 2.2.18 on 2021-02-11 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_fsm
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('gr', models.ManyToManyField(to='auth.Group')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fsm.Queue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок заявки')),
                ('description', models.TextField(verbose_name='Описания заявки')),
                ('state', django_fsm.FSMField(choices=[('Открыта', 'Открыта'), ('В прогрессе', 'В прогрессе'), ('Решена', 'Решена'), ('Переоткрыта', 'Переоткрыта'), ('Ошибка', 'Ошибка'), ('Закрыта', 'Закрыта')], default=('Открыта', 'Открыта'), max_length=50, verbose_name='Состояния заявки')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл')),
                ('data_create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsm.Queue', verbose_name='Зависит от')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
