# Generated by Django 2.2.19 on 2021-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='gr',
            field=models.ManyToManyField(blank=True, related_name='queue_set', related_query_name='queue', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
