# Generated by Django 2.2.19 on 2021-02-24 08:46

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0004_auto_20210224_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('Открыта', 'Открыта'), ('Ваполняется', 'Ваполняется'), ('Решена', 'Решена'), ('Переоткрыта', 'Переоткрыта'), ('Ошибка', 'Ошибка'), ('Закрыта', 'Закрыта')], default=('Открыта', 'Открыта'), max_length=50, verbose_name='Состояния заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Заголовок заявки'),
        ),
    ]
