# Generated by Django 2.2.19 on 2021-02-25 07:50

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0005_auto_20210224_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('Открыта', 'Открыта'), ('Ваполняется', 'Ваполняется'), ('Решена', 'Решена'), ('Переоткрыта', 'Переоткрыта'), ('Ошибка', 'Ошибка'), ('Закрыта', 'Закрыта')], default='Открыта', max_length=50, verbose_name='Состояния заявки'),
        ),
    ]
