# Generated by Django 2.2.19 on 2021-02-26 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0007_auto_20210226_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='the_importance',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Обычная', 'Обычная'), ('Высокая', 'Высокая'), ('Горит', 'Горит')], default='Обычная', max_length=26, verbose_name='Уровень важности'),
        ),
    ]
