# Generated by Django 2.2.19 on 2021-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0008_auto_20210226_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='the_importance',
            field=models.CharField(choices=[('warm', 'Горит'), ('high', 'Высокая'), ('common', 'Обычная'), ('low', 'Низкая')], default='high', max_length=26, verbose_name='Уровень важности'),
        ),
    ]
