# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

sql = """
UPDATE invoice_baseorder AS ib SET ib.content_type_id = (SELECT ct.id FROM django_content_type AS ct WHERE ct.app_label = 'afisha' AND ct.model = 'eventorder')
"""

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoice', '0002_baseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.RunSQL(sql),
    ]
