# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_baseorder'),
        ('adv', '0010_banner_is_alternate_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoice.BaseOrder')),
                ('client_name', models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0418\u043c\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_email', models.EmailField(blank=True, default=b'', max_length=254, verbose_name='E-mail \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('client_contacts', models.CharField(blank=True, default=b'', max_length=1024, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '\u041d\u043e\u0432\u044b\u0439'), (2, '\u041e\u0434\u043e\u0431\u0440\u0435\u043d'), (3, '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d')], default=1, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437 \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u044b',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u044b',
            },
            bases=('invoice.baseorder',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.FloatField(verbose_name='\u0426\u0435\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u043a\u043b\u0430\u043c\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430',
                'verbose_name_plural': '\u0420\u0435\u043a\u043b\u0430\u043c\u043d\u044b\u0435 \u0443\u0441\u043b\u0443\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='advorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='adv.Service', verbose_name='\u0420\u0435\u043a\u043b\u0430\u043c\u043d\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430'),
        ),
    ]
