# Generated by Django 2.2.19 on 2021-03-10 08:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('table_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliticTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время создания')),
                ('state', models.CharField(max_length=35, verbose_name='Состояния заявки')),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
