# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.utils.fields.file
import irk.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=irk.utils.fields.file.FileRemovableField(upload_to=b'img/site/pages/', validators=[irk.utils.validators.FileSizeValidator(max_size=5242880)], verbose_name='\u0424\u0430\u0439\u043b'),
        ),
    ]
