# Generated by Django 3.2.5 on 2021-07-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=invoice.models.get_uuid, max_length=64, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('processed', 'Ожидание оплаты'), ('cancel', 'Отменен'), ('success', 'Успешно'), ('fail', 'Ошибка')], default='processed', max_length=16, verbose_name='Результат')),
                ('system', models.PositiveIntegerField(blank=True, null=True, verbose_name='Способ платежа')),
                ('invoice', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер операции оператора')),
                ('amount', models.FloatField(verbose_name='Сумма заказа')),
                ('currency', models.CharField(blank=True, choices=[('RUB', 'Рубли'), ('USD', 'Доллары США'), ('EUR', 'Евро')], default='RUB', max_length=3, null=True, verbose_name='Валюта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('performed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('company', models.CharField(choices=[('moneta', 'Монета.ру'), ('apple', ' App Store')], default='moneta', max_length=16, verbose_name='Платежная компания')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Сумма заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='invoice.invoice', verbose_name='Платеж')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
