# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

from django.db import migrations
import irk.news.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u041e\u043f\u0442\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0440\u0430\u0437\u043c\u0435\u0440 \u0444\u043e\u0442\u043e 805\u0445536. \u041f\u0440\u043e\u043f\u043e\u0440\u0446\u0438\u044f 3:2.', null=True, upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='w_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 940\u0445405 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439.', null=True, upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0428\u0438\u0440\u043e\u043a\u043e\u0444\u043e\u0440\u043c\u0430\u0442\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 60x60 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', null=True, upload_to=b'img/site/polls/choice/', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
