# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0022_auto_20190313_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fb_url',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Facebook'),
        ),
        migrations.AlterField(
            model_name='event',
            name='inst_url',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Instagram'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ok_url',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vk_url',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0412\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'),
        ),
    ]
