# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0023_auto_20190424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u043e\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u0434\u043e\u0431\u0440\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_commercial',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u043e\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
