# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_baseorder'),
        ('afisha', '0028_auto_20201204_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoice.BaseOrder')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventorder_event', to='afisha.Event', verbose_name='\u0421\u043e\u0431\u044b\u0442\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
            bases=('invoice.baseorder',),
        ),
    ]
