# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20181211_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_auto_disable_comments',
            field=models.BooleanField(db_index=True, default=True, verbose_name='\u041e\u0442\u043a\u043b\u044e\u0447\u0430\u0442\u044c \u043a\u043e\u043c\u043c\u0435\u043d\u0430\u0440\u0438\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 1180\u0445560 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0428\u0438\u0440\u043e\u043a\u043e\u0444\u043e\u0440\u043c\u0430\u0442\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_bigfoot',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f \u0441 \u0431\u043e\u043b\u044c\u0448\u0438\u043c\u0438 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='metamaterial',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 1180\u0445560 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0428\u0438\u0440\u043e\u043a\u043e\u0444\u043e\u0440\u043c\u0430\u0442\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 1180\u0445560 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0428\u0438\u0440\u043e\u043a\u043e\u0444\u043e\u0440\u043c\u0430\u0442\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
