# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20190412_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basematerial',
            name='author',
            field=models.CharField(blank=True, max_length=250, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
    ]
