# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-30 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_author_charfield_20190430_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='caption_short',
        ),
    ]
