# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20190516_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndex',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='article_index', serialize=False, to='news.BaseMaterial', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('position', models.BigIntegerField(default=irk.utils.helpers.big_int_from_time, editable=False, verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('is_super', models.BooleanField(db_index=True, default=False)),
                ('stick_position', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('stick_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u0438\u044f')),
            ],
        ),
    ]
