# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_tildaarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.PositiveIntegerField(choices=[(0, b'\xd0\xbf\xd0\xbe \xd1\x83\xd0\xbc\xd0\xbe\xd0\xbb\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8e'), (2, b'\xd0\xba\xd1\x83\xd1\x80\xd1\x81\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb7\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba'), (1, b'\xd1\x81 \xd1\x84\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9 \xd1\x84\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xb5\xd0\xb9')], default=0, verbose_name='\u0428\u0430\u043f\u043a\u0430 \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
