# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_remove_unkind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=250, verbose_name='\u041f\u043e\u043b\u0435')),
                ('value', models.CharField(blank=True, max_length=1000, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.BaseMaterial')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0442\u0430-\u043f\u043e\u043b\u0435',
                'verbose_name_plural': '\u041c\u0435\u0442\u0430-\u043f\u043e\u043b\u044f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='postmeta',
            unique_together=set([('material', 'key')]),
        ),
    ]
