# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20191227_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindex',
            name='material',
        ),
        migrations.DeleteModel(
            name='ArticleIndex',
        ),
    ]
