# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models
import irk.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_remove_article_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(default=irk.utils.helpers.big_int_from_time, editable=False, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('admin_position', models.SmallIntegerField(blank=True, null=True, verbose_name='\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0430\u0434\u043c\u0438\u043d\u043e\u043c')),
                ('is_super', models.BooleanField(db_index=True, default=False)),
                ('stick_position', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('stick_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u0435\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_index', to='news.BaseMaterial', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='articleindex',
            index_together=set([('is_super', 'position', 'admin_position')]),
        ),
    ]
