# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import irk.news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_recreate_article_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveentry',
            name='created',
            field=models.TimeField(blank=True, default=irk.news.models.default_now_time, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='postmeta',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmeta', to='news.BaseMaterial'),
        ),
    ]
