# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import irk.news.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20200122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basematerial',
            name='social_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 940x445', null=True, upload_to=irk.news.models.social_card_upload_to, verbose_name='\u0424\u043e\u043d \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=irk.news.models.category_image_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='flash',
            name='video_thumbnail',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/news/flash', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 960\xd7&infin; \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=b'img/site/news/infographic', verbose_name='\u0418\u043d\u0444\u043e\u0433\u0440\u0430\u0444\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='preview',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 940x445 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=b'img/site/news/infographic', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='thumbnail',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 300\xd7200 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=b'img/site/news/infographic', verbose_name='\u041c\u0438\u043d\u0438\u0430\u0442\u044e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='liveentry',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/news/live', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, upload_to=irk.news.models.wide_image_upload_to, verbose_name='\u0411\u043e\u043b\u044c\u0448\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='socialpultupload',
            name='image',
            field=irk.utils.fields.file.FileRemovableField(upload_to=irk.news.models.social_pult_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'gif', b'jpg', b'jpeg', b'png', b'bmp', b'tif', b'mp4', b'avi', b'mkv', b'3gp', b'mov', b'webm', b'm4v', b'mpeg'])], verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0438\u043b\u0438 \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='background_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f: 1920x250', null=True, upload_to=b'img/site/news/subject', verbose_name='\u0444\u043e\u043d\u043e\u0432\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='home_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f: 1920x400', null=True, upload_to=b'img/site/news/subject', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0433\u043b\u0430\u0432\u043d\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='social_image',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 940x445', null=True, upload_to=irk.news.models.social_card_upload_to, verbose_name='\u0424\u043e\u043d \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='tildaarticle',
            name='archive',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.news.models.tilda_upload_to, verbose_name='\u0418\u043c\u043f\u043e\u0440\u0442 \u0438\u0437 \u0444\u0430\u0439\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=irk.utils.fields.file.ImageRemovableField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440: 800x378 \u043f\u0438\u043a\u0441\u0435\u043b\u0435\u0439', upload_to=b'img/site/news/video', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e'),
        ),
    ]
