# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expert_person'),
        ('news', '0040_delete_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basematerial',
            name='persons',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
