# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_remove_article_is_bigfoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='official_comment_bind',
            field=models.URLField(blank=True, default=b'', max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043e\u043f\u0440\u043e\u0432\u0435\u0440\u0433\u0430\u0435\u043c\u0443\u044e \u043d\u043e\u0432\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='news',
            name='official_comment_link',
            field=models.URLField(blank=True, default=b'', max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043f\u0435\u0440\u0432\u043e\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='news',
            name='official_comment_logo',
            field=models.ImageField(blank=True, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 \u043e\u0442: 128\u0445128 px', upload_to=b'img/site/news/official_comment_logo/', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430 \u0446\u0438\u0442\u0430\u0442\u044b \u0438\u043b\u0438 \u0444\u043e\u0442\u043e \u0430\u0432\u0442\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='news',
            name='official_comment_name',
            field=models.CharField(blank=True, default=b'', max_length=300, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='news',
            name='official_comment_text',
            field=models.CharField(blank=True, default=b'', max_length=300, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
