# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import irk.adv.models
import irk.adv.validators
import irk.utils.fields.file
import irk.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0008_auto_20190212_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bgimage',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/adv/banners/', verbose_name='\u0444\u043e\u043d (\u043b\u0435\u0432.)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='bgimage2',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=b'img/site/adv/banners/', verbose_name='\u0444\u043e\u043d (\u043f\u0440\u0430\u0432.)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='dummy',
            field=irk.utils.fields.file.ImageRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, verbose_name='\u0417\u0430\u0433\u043b\u0443\u0448\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='file',
            name='html5',
            field=irk.utils.fields.file.FileArchiveField(blank=True, null=True, upload_to=irk.adv.models.upload_html5_file, validators=[irk.adv.validators.validate_html5_file, django.core.validators.FileExtensionValidator(allowed_extensions=[b'zip'])], verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 html5'),
        ),
        migrations.AlterField(
            model_name='file',
            name='main',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=(b'swf', b'gif', b'jpg', b'jpeg', b'png'))], verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='file',
            name='main_320',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=(b'swf', b'gif', b'jpg', b'jpeg', b'png'))], verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0434\u043b\u044f \u0448\u0438\u0440\u0438\u043d\u044b 320'),
        ),
        migrations.AlterField(
            model_name='file',
            name='main_420',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=(b'swf', b'gif', b'jpg', b'jpeg', b'png'))], verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0434\u043b\u044f \u0448\u0438\u0440\u0438\u043d\u044b 420'),
        ),
        migrations.AlterField(
            model_name='file',
            name='main_768',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=(b'swf', b'gif', b'jpg', b'jpeg', b'png'))], verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0434\u043b\u044f \u0448\u0438\u0440\u0438\u043d\u044b 768'),
        ),
        migrations.AlterField(
            model_name='file',
            name='video',
            field=irk.utils.fields.file.FileRemovableField(blank=True, help_text='\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c \u0435\u0441\u043b\u0438 \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d webm', null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[irk.utils.validators.FileSizeValidator(max_size=16777216), django.core.validators.FileExtensionValidator(allowed_extensions=[b'mp4'])], verbose_name='\u0412\u0438\u0434\u0435\u043e (mp4)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='video_ogg',
            field=irk.utils.fields.file.FileRemovableField(blank=True, null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[irk.utils.validators.FileSizeValidator(max_size=16777216), django.core.validators.FileExtensionValidator(allowed_extensions=[b'ogg'])], verbose_name='\u0412\u0438\u0434\u0435\u043e (ogg)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='video_webm',
            field=irk.utils.fields.file.FileRemovableField(blank=True, help_text='\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c \u0435\u0441\u043b\u0438 \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d mp4', null=True, upload_to=irk.adv.models.get_upload_to_path, validators=[irk.utils.validators.FileSizeValidator(max_size=16777216), django.core.validators.FileExtensionValidator(allowed_extensions=[b'webm'])], verbose_name='\u0412\u0438\u0434\u0435\u043e (webm)'),
        ),
    ]
