# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0009_auto_20200210_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_alternate_external',
            field=models.BooleanField(default=False, verbose_name='\u0427\u0435\u0440\u0435\u0434\u043e\u0432\u0430\u0442\u044c \u0441 \u0432\u043d\u0435\u0448\u043d\u0438\u043c \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u043c'),
        ),
    ]
