# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import irk.gallery.models
import irk.utils.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=irk.utils.fields.file.ImageRemovableField(upload_to=irk.gallery.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=(b'gif', b'jpg', b'jpeg', b'png', b'bmp', b'tif'))], verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
