# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20180418_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='booking_visible',
            field=models.BooleanField(default=False, verbose_name='\u0412\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u0432 \u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slugs',
            field=models.CharField(help_text='\u0414\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u043c \u0438 \u043d\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0442\u044c \u0432 \u0441\u0435\u0431\u0435 \u0434\u0440\u0443\u0433\u0438\u0435 \u0430\u043b\u0438\u0430\u0441\u044b. \u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 news-some \u043d\u0435 \u043f\u043e\u0434\u043e\u0439\u0434\u0435\u0442', max_length=50, unique=True, verbose_name='\u0410\u043b\u0438\u0430\u0441\u044b'),
        ),
    ]
