# Generated by Django 2.2.19 on 2021-02-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0005_auto_20210224_0846'),
        ('djangoChat', '0003_auto_20210224_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskchat', to='fsm.Task'),
        ),
    ]
