# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_auto_20200210_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=191, unique=True, verbose_name='\u0410\u043b\u0438\u0430\u0441'),
        ),
    ]
